apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: localbuild-app
data:
  config.json: |
    {
      "apiVersion": "v1",
      "environment": "local",
      "logLevel": "info",
      "features": {
        "metrics": true,
        "logging": true
      }
    }
