apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localbuild-app-ingress
  namespace: localbuild-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: localbuild.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: localbuild-app
                port:
                  number: 80
